---
title: "Data Wrangling and Statistics in R"
author: "J Kyle Armstrong PhD"
output: slidy_presentation
---


# R

Getting Started

```{r, eval=FALSE}
install.packages('tidyverse')
```

```{r}
library('tidyverse')
```


# Read in data

Often the first step is to connect to the data:

```{r, eval=FALSE}

con <- DBI::dbConnect(RMySQL::MySQL(), 
  host = "database.company.com",
  user = "user_name",
  password = rstudioapi::askForPassword("Database password")
)

A_DATA_TBL <- tbl(con, "table_name")

```


```{r read-in-data , eval=FALSE}
A_DATA <- readRDS('A_DATA.RDS')
A_DATA <- readxl::read_excel('A_DATA.xlsx') # don't forget about sheets! 
```

# Read CSV

```{r real-read-in }
A_DATA <- readr::read_csv('A_DATA.csv')
```



# Transform and Summarise Data

Use dplyr and the tidyverse to get summary data 

```{r}
A_DATA %>%
  mutate(over_50 = if_else(Age > 50, 1, 0)) %>%
  group_by(DIABETES, over_50) %>%
  summarise(n = n(),
            mean_age = mean(Age, na.rm = TRUE),
            sd_age = sd(Age, na.rm = TRUE),
            .groups = 'keep')
```

# Piviot Longer

```{r}
A_DATA %>%
  mutate(over_50 = if_else(Age > 50, 1, 0)) %>%
  group_by(DIABETES, over_50) %>%
  summarise(n = n(),
            mean_age = mean(Age, na.rm = TRUE),
            sd_age = sd(Age, na.rm = TRUE),
            .groups = 'keep') %>%
  pivot_longer(cols=c(n,mean_age),
               names_to = "statistic",
               values_to = "value")
```

# Get Counts by Groups

```{r}
A_DATA %>%
  filter(!is.na(Grade_Level)) %>%
  group_by(Gender, Race) %>%
  tally()
```

# Pivot Wider

```{r}
A_DATA %>%
  filter(!is.na(Grade_Level)) %>%
  group_by(Gender, Race) %>%
  tally() %>%
  ungroup() %>%
  pivot_wider(Race, names_from= Gender, values_from = n)
```

# Export Data 

Write and Save Data

```{r write-out-data, eval=FALSE}
A_DATA %>% saveRDS('A_DATA.RDS')
A_DATA %>% openxlsx::write.xlsx('A_DATA.xlsx') 
A_DATA %>% readr::write_csv('A_DATA.csv')
```


# Stats

# t-test
```{r}
Target_Age <- (A_DATA %>%
  filter(DIABETES == 1))$Age

Control_Age <- (A_DATA %>%
  filter(DIABETES == 0))$Age

t.test(Target_Age, Control_Age,
       alternative = "two.sided",
       conf.level = 0.95) %>%
  broom::tidy()
```


# t-test
```{r}
t.test(Age ~ DIABETES,
       data = A_DATA %>% filter(!is.na(DIABETES)),
       alternative = "two.sided",
       conf.level = 0.95)
```

# ks-test
```{r}
A_DATA %>%
  filter(!is.na(DIABETES))%>%
  ggplot(aes(x=Age, color=as.factor(DIABETES))) +
  stat_ecdf() + 
  labs(title = "K-S Test")
```

# ks-test 
```{r}
ks.test(Target_Age, Control_Age,
       alternative = "two.sided") %>%
  broom::tidy() 
```



### chi-square test

### anova


## Models

### glm


## Model Evaluation

